### ISSUE TITLE
set-env deprecation warning

### ISSUE THREAD

**Issue by vintagepc** [openrndr/setup-opengl#3]
This action throws warnings that set-env is being deprecated soon.

```
Run openrndr/setup-opengl@21a61c3
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
/home/runner/work/_actions/openrndr/setup-opengl/21a61c3/setup-opengl.sh
```

**Comment by edwinRNDR** [comment]
Thanks! I will have a look at switching to environment files.

**Comment by vintagepc** [comment]
FYI the deprecation date is Nov 16th. Any update?

**Comment by edwinRNDR** [comment]
@vintagepc thanks for the reminder! I have just published `v1.1` which has fixes for the `set-env` deprecations

**Comment by vintagepc** [comment]
Great, thank you! This has been a fantastic tool for creating automated unit tests with GL code :)

**Comment by ryancdavison** [comment]
I'm still seeing this issue today:
from my Action:  
```
    - uses: actions/checkout@v2
    - uses: openrndr/setup-opengl@v1
    - run: xvfb-run glxinfo
```
Output:
```
Run openrndr/setup-opengl@v1
  env:
    LD_LIBRARY_PATH: /home/runner/work/liquidfun/liquidfun/~/.clang/lib:
    DYLD_LIBRARY_PATH: /home/runner/work/liquidfun/liquidfun/~/.clang/lib:
Error: Unable to process command '::set-env name=LD_LIBRARY_PATH::mesa-18.2.3/usr/local/lib/x86_64-linux-gnu' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: Unable to process command '::set-env name=GALLIUM_DRIVER::swr' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by vintagepc** [comment]
You need to edit your action to be `uses: openrndr/setup-opengl@v1.1` or (`@latest`)

**Comment by ryancdavison** [comment]
Thank you for your quick reply and help!  Everything worked.

**Comment by edwinRNDR** [comment]
The `README.md` still mentioned `@v1`, that was likely what caused the confusion. Updated it with a reference to the latest version.

**Comment by hamoid** [comment]
Maybe the PR I sent changing two mentions of @v1 was not noticed? :)

**Comment by edwinRNDR** [comment]
@hamoid ooops! I see it now and merged it in, thanks!
